### ISSUE TITLE
Cannot set font size or figure size in pp_matrix_from_data

### ISSUE THREAD

**Issue by Stardestroyer0** [wcipriano/pretty-print-confusion-matrix#15]
When using pp_matrix_from_data with parameters figsize and fz, these does not seems to have any effects. Reading the library, it seems they are redefined right after being passed as parameter (as shown in picture). Removing those assignment seems to fix the issue for me, but I don't know if it is a good way to do it.
![immagine_2022-05-19_221542257](https://user-images.githubusercontent.com/55991056/169396934-8807e73b-f4bd-4c9e-bac8-da0a2f7bff3f.png)
.

**Comment by Financialnomad** [comment]
Hello StarDestroyer, thank you for finding it. Can you please create a pull request for all of us who are suffering from this? thank you

**Comment by wcipriano** [comment]
Ok @Financialnomad  I will review it !

**Comment by wcipriano** [comment]
Hi @Stardestroyer0 !
Thank you for your report !

It has been solved in the current version.
You can get the new version, it's available in the official PyPI ([here](https://pypi.org/project/pretty-confusion-matrix/)).


Please, update your version !

Best regards ;)
