### ISSUE TITLE
cmap

### ISSUE THREAD

**Issue by BenyaminZojaji** [wcipriano/pretty-print-confusion-matrix#16]
Hey,
Would you pls provide a complete color map on readme.md? that will be great.

**Comment by DamienAllonsius** [comment]
In the meantime, have a look at : https://matplotlib.org/stable/tutorials/colors/colormaps.html#choosing-colormaps-in-matplotlib

**Comment by wcipriano** [comment]
Hello @BenyaminZojaji  !
Thank you for your report !

Hi @DamienAllonsius , thank you for your contribution !

It's done ! 
New README version avalilable !

I would like to advertise you that I released version 0.2.0 and it is available in the [official PyPI](https://pypi.org/project/pretty-confusion-matrix/), please update your version!

Best regards  ;)
