### ISSUE TITLE
Save matrix as image

### ISSUE THREAD

**Issue by Llugway** [wcipriano/pretty-print-confusion-matrix#20]
Hello,

Is it possible to save your confusion matrix as image in the code  ?

I don't think, but i prefer ask :p.

Thanks for your work !

Lugway

**Comment by kosmar2011** [comment]
Just run plt.savefig("path/to/image.png") after pp_matrix or pp_matrix_from_data

**Comment by wcipriano** [comment]
Hello @Llugway  !
Thank you for your question. Sorry for delay, but I'm in now and I'll support the project !

It's done !
It'll released in the next version, soon...

Best regards ;)
