### ISSUE TITLE
Python 3.11.7

### ISSUE THREAD

**Issue by JoaoFerreira165** [wcipriano/pretty-print-confusion-matrix#24]
Can i use this library with python version = 3.11.7 ? 
because im receiving this error:
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.7.1,<3.11; 0.1.1 Requires-Python >=3.7.1,<3.11
ERROR: Could not find a version that satisfies the requirement pretty-confusion-matrix (from versions: none)
ERROR: No matching distribution found for pretty-confusion-matrix

**Comment by wcipriano** [comment]
Hello JoaoFerreira165 !
Thank you for your report !

Yes, now you can use the library in python 3.11.
This week I've updated a version with dependencies update, and support for python 3.11.

I released the version 0.2.0, and It's available in the official Python package index:
https://pypi.org/project/pretty-confusion-matrix/

As you can see int the screenshot, I've tested in the python version 3.11.9 and it worked fine.
![python-3 11 9_2024mai 8-214623](https://github.com/wcipriano/pretty-print-confusion-matrix/assets/25016649/736bfe74-b484-4a1b-bef8-bc65118c341e)



Please try again and tell me if you have success!

Best regards !

**Comment by JoaoFerreira165** [comment]
Hello,
It worked, thank you very much, I really appreciate it
