### ISSUE TITLE
Matplotlib 3.1.1 breaks seaborn heatmaps

### ISSUE THREAD

**Issue by Stefn93** [wcipriano/pretty-print-confusion-matrix#3]
By executing the actual code the graph plot is cut at the top and at the bottom.

Solution.
Set heatmap limits manually by adding the following code at the end of "pretty_plot_confusion_matrix" function:
`bottom, top = ax.get_ylim()`
`ax.set_ylim(bottom + 0.5, top - 0.5)`

Reference:
https://stackoverflow.com/questions/56942670/matplotlib-seaborn-first-and-last-row-cut-in-half-of-heatmap-plot

**Comment by wcipriano** [comment]
Hello @Stefn93 !

Thank you for your report !
Sorry for delay, but I'm IN now and I'll support the project again!

I couldn't  check this behavior in the current version.
Probably he updated of the versions of the dependencies has been solved the problem.

As you can see int the screenshot, I've tested in the python version 3.11.9 and it worked fine.
![graph-plot_2024mai8-221447](https://github.com/wcipriano/pretty-print-confusion-matrix/assets/25016649/1a50eefa-0189-4794-88f3-b4bac161a141)


Please try again and tell me if you have success!

I would like to inform you that I released version 0.2.0 and it is available in the official Python package index: 
https://pypi.org/project/pretty-confusion-matrix/


Best regards !

**Comment by wcipriano** [comment]
I'm closing this issue, because it has already been resolved, but you can contact me in case of doubt.
