### ISSUE TITLE
how do I replace class A, class B,...  in the output plot with custom string labels such as "Cat", "Dog", "Mouse", ....

### ISSUE THREAD

**Issue by BigWheel92** [wcipriano/pretty-print-confusion-matrix#4]

**Comment by BigWheel92** [comment]
Incase anyone need help: 
 **the order must be the same, i.e., cat will be assigned to the class having int label of 0, dog will be assigned to the class having int label of 1,  so on and so forth**

columns=['Cat', 'Dog', 'Mouse']
plot_confusion_matrix_from_data(y_test, y_pred, columns)

**Comment by wcipriano** [comment]
Hello @BigWheel92 
I'll put this in the readme.
Thank you  for contribution!

**Comment by wcipriano** [comment]
Hello @BigWheel92  !
Thank you for your report !

It's done !
New README version avalilable !

I would like to advertise you that I released version 0.2.0 and it is available in the [official PyPI](https://pypi.org/project/pretty-confusion-matrix/), please update your version!

Best regards ;)
